### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by tiptonnet** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can#10]
Do you think this would work on an ESP32 with MicroPython?

**Comment by vyas-shubham** [comment]
After a very quick cursory reading, it might be possible. But it would require rewriting the parts that use the SocketCAN (`socket`) methods in the code with equivalents from micropython and accordingly connect the CAN cables. 

As I do not have the hardware with me, I cannot test this.

**Comment by tiptonnet** [comment]
Fantastic, I expected some rewriting.  Thanks.

**Comment by vyas-shubham** [comment]
Alright. Let me know if you need any further help and if you have a driver working, do feel free to create a pull request.
