### ISSUE TITLE
T-Motor AK80 series different motor parameters for firmware versions V1.0, V1.1., V2.0

### ISSUE THREAD

**Issue by babel-robotics** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can#4]
T-Motors updated their motor controller board firmware several times lately and at the same time the motor parameters, which must be set in the motor driver changed.

The following table kindly provided by T-Motors displays the motor parameters for the AK-Series line up. We noticed that for AK80-6 V2.0 and AK80-9 V1.1 the speed limits are wrong and that **V_MIN = -22.5, V_MAX = 22.5** works best, while other parameters seem to be correct.

![t-motor_ak_series_constants](https://user-images.githubusercontent.com/85624679/148370728-c8b31363-bb32-498a-a063-8a87efb3ae7f.png)

We furthermore found these instructions [CubeMars_AK_Series_Program_Refresh_Guide_V2.0.pdf](https://github.com/dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can/files/7821233/CubeMars_AK_Series_Program_Refresh_Guide_V2.0.pdf), as well  provided by T-Motors, useful to keep track with various existing firmware versions for AK series motors, since it not very well documented on their website [store.tmotor.com](https://store.tmotor.com/category.php?id=97).

**Comment by shivesh1210** [comment]
addressed in c003ed1a136a1553c70b2c74f2b90f688c4cef29 and 4484dce3b036b1613eb5a341c66e8364b027b6b5
