### ISSUE TITLE
Issue with motor parameters

### ISSUE THREAD

**Issue by ekrimsk** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can#7]
This isn't actually an issue with your code, I'm curious where you got the motor parameters for the V1.1 firmware. I have purchased two AK80-6 that say they have V2.0 firmware on boot, but with V_max = 38.2 the motor runs slow and the V_max that get's the position and velocities to line up experimentally is ~21.5. Tmotor sent me new firmware to flash (seemingly V1.9), but this seems to work with V_max = 45 and P_max = 12.5, which isn't listed in any documentation. I also have a AK80-9 where the velocity only makes sense with V_max = 50. I have tested this independently with the canmotorlib and with R-link tool Tmotor sells. 

Curious to hear if you ran into any parameter issues, or have any other docs from Tmotor. You can mark this as closed and email me directly (ekrimsky@stanford.edu). Thank you!

**Comment by vyas-shubham** [comment]
Hi,

Unless there's something that can't be made public, I suggest having the conversation here as it can be found by other people who might be having similar issues. Your experience is very similar to ours actually. The V1 firmware, the one that came with our first motor purchases about a year ago, had the velocity constants at +-45. However, that firmware had lots of noise in the measurements so we upgraded to V2, and then the parameters changed. We got the new parameters via email from T-motors. After this, we ordered a new batch of motors and they came with V1.1. We considered upgrading the firmware but this version performed even better torque control than V2 so we decided to keep this. Similar to your experience, we found experimentally that Vecloty constants are +-22.5 (basically, half of 45 ;) ) for this version, which also seems to be the case for you. So I'd suggest trying simple position/velocity control with `AK80_6_V1p1_PARAMS` and let us know how it goes. In our experience, T-Motors does not have very good documentation for their versions/parameters but the motors are still quite good and worth spending time to estimate the constants.

In our communication with T-Motors, we received the following if that's of any help:
![image](https://user-images.githubusercontent.com/43845118/155837244-89090199-0fe3-4eff-9d3f-fa69393c41b2.png)


I'd be highly surprised if your motor constants are different from the ones we provide (if so, do make a pull request with them!). So I'd suggest trying out these values and seeing which perform as expected. It is not the ideal way forward, but it's one way...

Hope this helps!

Shubham

**Comment by ekrimsk** [comment]
How did you identify the firmware version on the motors? Is it just from the startup message that motor prints over uart? Do you have the V1.1 firmware file? Thanks for the help

**Comment by vyas-shubham** [comment]
I remember it indeed being the version number in the startup text printed over serial.  Also in some of the communications with T-Motors as well. We do have the .bin/hex files of the firmware. I will try to upload them soon.

**Comment by ekrimsk** [comment]
Any firmware files you could share would be incredibly useful. I finally identified parameters for the V1.9 firmware I had flashed, only to find that the CAN communication becomes unreliable quickly (this did not happen with the original V2.0 firmware but I don't have access to that file)

**Comment by vyas-shubham** [comment]
Here is the link to the set of firmware we have at DFKI for the AK80-6 actuators: [Link](https://we.tl/t-T4G0e84JaH)

The **_extracted** files are the firmware we extracted from the motors we have and the **_fromTMotors** are the firmware files we have from T-Motors. The firmware we use currently is *AK80-6_new_img_10092021_extracted.hex*

**Comment by ekrimsk** [comment]
Thanks a ton! The serial for this firmware prints "Version 2.0", but the correct velocity parameter is definitely 22.5. I just want to confirm that this one is the V1.1 firmware (and that the print out is just incorrect).

**Comment by vyas-shubham** [comment]
Indeed. I'm also not sure about why it prints Version 2.0. Will check that later and submit a fix to the version numbers. Glad to hear its working now!

**Comment by williamcmartin** [comment]
@vyas-shubham: Would it be possible to get another upload of those .hex/.bin files for the AK80-6? I came across this thread while debugging the same issue but unfortunately the link above has expired. (I have an unfortunate amount of position/velocity noise on my AK80-6 so I'm playing a bit of firmware roulette.)

**Comment by vyas-shubham** [comment]
@williamcmartin Here is another temporary link with the firmware we have: https://we.tl/t-xiuLqkxGWx

**Comment by Keikibayev** [comment]
Hi there,
I have a new AK80-64 actuator, but there is no option in Cubemars software for this motor. I have asked them to send a firmware to update, but Tmotor asked to purchase other actutor, which is in the software list. So I wanted to extract firmware from actuator myself. Could you describe how does it possible? and could you send a link to your firmware to be aknowledge with them? Thanks.

**Comment by vyas-shubham** [comment]
@Keikibayev If the motor still uses STM32 inside, you can use stlink to read the firmware binary stored in the flash. I am pretty sure that the firmware for AK80-6 is different from AK80-64 as the conversion constants for position/velocity/torque which are stored on the firmware are different.

**Comment by Keikibayev** [comment]
@vyas-shubham thanks for reply. I will try to read it via stlink. Anyway I am receiving gibberish while reading com port by its r-link in teraterm, though connection parameters are ok (baud, flowconctrol, etc.). Have you face the same issue? Should I have servo mode which I do not have in my actuator (only mit mode)? Do I need to build an Arduino based controller to control my actuator? Sorry for this stupid questions, but I am a new in this matter.

**Comment by vyas-shubham** [comment]
@Keikibayev Until recently, we were using a Windows computer for serial communication with the T-Motor drives as the serial communication application (TeraTerm) was better there. We had to switch between windows and Linux constantly for initial setup and testing. TeraTerm, like other serial communication libraries, required configuring the baud rate (921600) to have proper communication.
I recently found a new application called screen for Linux which is simple to use and works the same as TeraTerm. So we don't need to switch to a windows computer.
 
Example usage: 

```
sudo apt-get install screen
screen /dev/ttyUSB0 921600 
```

**Comment by Siwakonrome** [comment]
Hi. I try to control AK60-60 in Ubuntu 20.0.4 with TMotorCANControl Api in python lib but when i run check motor connection method python script it's return (RTNETLINK answers: Operation not supported).  I have to install some driver? to make TMotorCANControl Api find Can0? (I use R-Link can protocol)

**Comment by vyas-shubham** [comment]
@Siwakonrome  I cannot answer much about TMotorCANControl library issues as I have not developed/used that library. This is a different driver (more low-level) for the same type of motors but these are 2 different libraries. I would suggest asking at their main repo here: https://github.com/neurobionics/TMotorCANControl
