### ISSUE TITLE
Moving Motor Using Degree Commands

### ISSUE THREAD

**Issue by TonyLiu836** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can#8]
Hi, 

I was wondering if you could explain how the send_deg_command works in the can_motorlib_test.py file. For the moving 180 degrees test, 0 degrees was passed and 90 was passed for vel_des. I'm not understanding how the motor should move 180 degrees when only a desired velocity value is used.

Thank you very much.

**Comment by vyas-shubham** [comment]
Hi!

`send_deg_command(0, 90, 0, 2, 0)` has the following arguments: position desired, velocity desired, Kp (position gain), Kd (velocity gain/damping), and feedforward/commanded torque.

Internally, the motor computes the following for commanding the controller: (position_desired * Kp) + (velocity_desired * Kd) + feedforward_torque.

So in the `can_motorlib_test.py`, the above command is used which commands 90 deg/s velocity with velocity gain (Kd) as 2. As Kp is set to zero, no position control is applied. Same for zero torque. 

On line 47, you can see `time.sleep(2)`. This causes the script to wait 2 seconds before sending the next command which is zero velocity. As 90 deg/s is applied for 2 seconds, the motor is expected to rotate 180 degrees approximately if the motor parameters are correct.

hope this helps!

@TonyLiu836 If this solves your issue, I'm going to close this issue.
