### ISSUE TITLE
Unable to Receive CAN Frame

### ISSUE THREAD

**Issue by anflores** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can#9]
Hi,

First of all, thank you for making this repository and also for the nice documentation. I am unable to run an AK10-9 motor using your code. I'm using Peak's system PCAN-USB, but when I try to run the code I get a time-out error, saying that the socket is unable to receive CAN frame. I wonder if this problem comes from the wire connections or from the motor itself.

I have the motor connected to a 24v power supply, and the two wires of the CAN bus are connected to the PCAN-USB through an adaptor. Ground from the motor supply is also connected to this adaptor, and a resistor of 120 Ohms is placed between CANH and CANL in both ends. I would really appreciate any help on this, thank you in advance

**Comment by vyas-shubham** [comment]
Hi.

Glad to hear you are using the code. We have previously gotten AK10-9 V2.0 (this is important as I understand only V2.0 has the MIT mode which this driver uses) to work with this driver.

`socket is unable to receive CAN frame` error usually means that the message is not received from the motor. Could be quite a few reasons for this:

- The Motor is not configured correctly. Maybe the motor is not in MIT Mode? Check T-Motor's documentation for how to enable MIT mode using their configuration utility.
- socketcan interface is not set up properly. You can try understanding and using `setup_caninterface.sh` from this repo to set up the CAN interface. Check if `can0` (or another number) appears in the list of interfaces. Can also use the `candump` utility to verify the messages on the interface.
- Wiring error... The easiest way to verify is to use another motor (AK80-6 for example) and very the connections. Else, switching High and Low is an easy test. The next step is always getting an oscilloscope to see the CAN bus...
- As I understand you only need 120 Ohms on one end... But this shouldn't affect much...
- Least likely, but possible, is that the motor is not working... We've had the CAN transceiver chips on our AK10-9 burn and could see it with a multimeter once we opened the motor...

**Comment by anflores** [comment]
Thank you for the fast response! Actually, my motor is AK10-9 V1.1, does this mean that the driver cannot run this motor? Is there any way to update it to V2.0 without purchasing another Driver board?

EDIT:

Ok, I can control the motor in MIT mode with the CubeMars software in Windows using the R-LINK, so I guess it should be possible to do it over the PCAN-USB system in ubuntu (?)

**Comment by vyas-shubham** [comment]
Yup! It does have MIT mode. You can see it in the manual here: https://store.tmotor.com/images/file/202208/251661393360838805.pdf

If you set it in the MIT mode, and verify the CAN connection (cables, socketcan, etc.), then I assume it should work. Another option is then to indeed debug using either `candump` or an oscilloscope. `candump` is an easier starting option.

**Comment by vyas-shubham** [comment]
@anflores Do let us know if it worked! So that we can then close this issue :)
